# ================================
# migrations/versions/001_initial_migration.py
# ================================

"""Initial migration

Revision ID: 001
Revises: 
Create Date: 2024-01-01 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers
revision = '001'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Users table
    op.create_table('users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(80), nullable=False),
        sa.Column('email', sa.String(120), nullable=False),
        sa.Column('password_hash', sa.String(255), nullable=False),
        sa.Column('first_name', sa.String(100), nullable=True),
        sa.Column('last_name', sa.String(100), nullable=True),
        sa.Column('phone', sa.String(20), nullable=True),
        sa.Column('mobile', sa.String(20), nullable=True),
        sa.Column('address', sa.Text(), nullable=True),
        sa.Column('postal_code', sa.String(10), nullable=True),
        sa.Column('city', sa.String(100), nullable=True),
        sa.Column('country', sa.String(100), nullable=True),
        sa.Column('company', sa.String(200), nullable=True),
        sa.Column('position', sa.String(100), nullable=True),
        sa.Column('sector', sa.String(100), nullable=True),
        sa.Column('vat_number', sa.String(50), nullable=True),
        sa.Column('siret_number', sa.String(50), nullable=True),
        sa.Column('user_type', sa.Enum('CLIENT', 'PROVIDER', 'ADMIN', name='usertype'), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('is_admin', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('last_login', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    
    # Events table
    op.create_table('events',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('organizer_id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(200), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('event_type', sa.Enum('PERSONAL', 'PROFESSIONAL', name='eventtype'), nullable=False),
        sa.Column('status', sa.Enum('DRAFT', 'PENDING', 'CONFIRMED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='eventstatus'), nullable=True),
        sa.Column('total_budget', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('budget_per_person', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('budget_type', sa.String(20), nullable=True),
        sa.Column('expected_participants', sa.Integer(), nullable=True),
        sa.Column('min_age', sa.Integer(), nullable=True),
        sa.Column('max_age', sa.Integer(), nullable=True),
        sa.Column('gender_target', sa.String(20), nullable=True),
        sa.Column('start_date', sa.DateTime(), nullable=True),
        sa.Column('end_date', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['organizer_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Providers table
    op.create_table('providers',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('company_name', sa.String(200), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('website', sa.String(200), nullable=True),
        sa.Column('category', sa.Enum('VENUE', 'DECORATION', 'TRANSPORT', 'CATERING', 'ANIMATION', 'ACTIVITY', 'COMMUNICATION', 'TECHNICAL', name='providercategory'), nullable=False),
        sa.Column('services', sa.Text(), nullable=True),
        sa.Column('intervention_zone', sa.Text(), nullable=True),
        sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('price_per_person', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('price_type', sa.String(50), nullable=True),
        sa.Column('average_rating', sa.Float(), nullable=True),
        sa.Column('total_ratings', sa.Integer(), nullable=True),
        sa.Column('is_verified', sa.Boolean(), nullable=True),
        sa.Column('is_premium', sa.Boolean(), nullable=True),
        sa.Column('subscription_end', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Venues table
    op.create_table('venues',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(200), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('address', sa.Text(), nullable=True),
        sa.Column('postal_code', sa.String(10), nullable=True),
        sa.Column('city', sa.String(100), nullable=True),
        sa.Column('country', sa.String(100), nullable=True),
        sa.Column('latitude', sa.Float(), nullable=True),
        sa.Column('longitude', sa.Float(), nullable=True),
        sa.Column('max_capacity', sa.Integer(), nullable=True),
        sa.Column('min_capacity', sa.Integer(), nullable=True),
        sa.Column('services', sa.Text(), nullable=True),
        sa.Column('equipment', sa.Text(), nullable=True),
        sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('price_per_person', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('price_per_hour', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('contact_person', sa.String(100), nullable=True),
        sa.Column('contact_position', sa.String(100), nullable=True),
        sa.Column('phone', sa.String(20), nullable=True),
        sa.Column('email', sa.String(120), nullable=True),
        sa.Column('website', sa.String(200), nullable=True),
        sa.Column('is_verified', sa.Boolean(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('venues')
    op.drop_table('providers')
    op.drop_table('events')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###

# ================================
# scripts/init_db.py
# ================================

"""Script d'initialisation de la base de données"""

from app import create_app, db
from app.models.user import User, UserType
from app.models.provider import Provider, ProviderCategory
from app.models.venue import Venue
from app.models.event import Event, EventType, EventStatus
from datetime import datetime, timedelta
import random

def init_database():
    """Initialiser la base de données avec des données de test"""
    
    app = create_app()
    
    with app.app_context():
        # Créer les tables
        db.create_all()
        
        print("Tables créées avec succès")
        
        # Créer un administrateur
        admin = User(
            username='admin',
            email='admin@creativecocktail.com',
            first_name='Admin',
            last_name='System',
            user_type=UserType.ADMIN,
            is_admin=True,
            is_active=True
        )
        admin.set_password('admin123')
        db.session.add(admin)
        
        # Créer des utilisateurs clients de test
        clients = []
        for i in range(10):
            client = User(
                username=f'client{i+1}',
                email=f'client{i+1}@example.com',
                first_name=f'Client{i+1}',
                last_name='Test',
                user_type=UserType.CLIENT,
                is_active=True,
                city=['Paris', 'Lyon', 'Marseille', 'Toulouse', 'Nice'][i % 5]
            )
            client.set_password('password123')
            clients.append(client)
            db.session.add(client)
        
        # Créer des prestataires de test
        providers_data = [
            {
                'company_name': 'Château de Versailles Events',
                'category': ProviderCategory.VENUE,
                'description': 'Location de salles prestigieuses pour vos événements',
                'city': 'Versailles'
            },
            {
                'company_name': 'Délices et Saveurs',
                'category': ProviderCategory.CATERING,
                'description': 'Traiteur gastronomique pour tous vos événements',
                'city': 'Paris'
            },
            {
                'company_name': 'Transport VIP',
                'category': ProviderCategory.TRANSPORT,
                'description': 'Solutions de transport haut de gamme',
                'city': 'Lyon'
            },
            {
                'company_name': 'Déco Événements',
                'category': ProviderCategory.DECORATION,
                'description': 'Décoration et mobilier pour événements',
                'city': 'Marseille'
            },
            {
                'company_name': 'Animation Pro',
                'category': ProviderCategory.ANIMATION,
                'description': 'Animations et spectacles pour tous âges',
                'city': 'Toulouse'
            }
        ]
        
        providers = []
        for i, provider_data in enumerate(providers_data):
            # Créer l'utilisateur prestataire
            user = User(
                username=f'provider{i+1}',
                email=f'provider{i+1}@example.com',
                first_name=f'Provider{i+1}',
                last_name='Test',
                user_type=UserType.PROVIDER,
                is_active=True,
                city=provider_data['city']
            )
            user.set_password('password123')
            db.session.add(user)
            db.session.flush()  # Pour récupérer l'ID
            
            # Créer le profil prestataire
            provider = Provider(
                user_id=user.id,
                company_name=provider_data['company_name'],
                category=provider_data['category'],
                description=provider_data['description'],
                is_verified=True,
                base_price=random.randint(500, 5000),
                average_rating=random.uniform(3.5, 5.0),
                total_ratings=random.randint(5, 50)
            )
            providers.append(provider)
            db.session.add(provider)
        
        # Créer des lieux de test
        venues_data = [
            {
                'name': 'Palais des Congrès de Paris',
                'city': 'Paris',
                'max_capacity': 1000,
                'base_price': 5000
            },
            {
                'name': 'Centre de Conférences Lyon',
                'city': 'Lyon',
                'max_capacity': 500,
                'base_price': 2500
            },
            {
                'name': 'Espace Marseille Provence',
                'city': 'Marseille',
                'max_capacity': 300,
                'base_price': 1500
            }
        ]
        
        venues = []
        for venue_data in venues_data:
            venue = Venue(
                name=venue_data['name'],
                city=venue_data['city'],
                max_capacity=venue_data['max_capacity'],
                base_price=venue_data['base_price'],
                is_verified=True,
                is_active=True
            )
            venues.append(venue)
            db.session.add(venue)
        
        # Créer des événements de test
        event_titles = [
            'Conférence Annuelle Tech 2024',
            'Mariage de Sophie et Pierre',
            'Séminaire Équipe Marketing',
            'Anniversaire Entreprise 10 ans',
            'Formation Leadership'
        ]
        
        for i, title in enumerate(event_titles):
            event = Event(
                title=title,
                organizer_id=clients[i].id if i < len(clients) else clients[0].id,
                event_type=EventType.PROFESSIONAL if i % 2 == 0 else EventType.PERSONAL,
                status=EventStatus.CONFIRMED,
                total_budget=random.randint(1000, 20000),
                expected_participants=random.randint(20, 200),
                start_date=datetime.now() + timedelta(days=random.randint(30, 365)),
                end_date=datetime.now() + timedelta(days=random.randint(30, 365) + 1)
            )
            db.session.add(event)
        
        # Valider toutes les modifications
        db.session.commit()
        
        print("Données de test créées avec succès")
        print("Utilisateurs créés:")
        print("- Admin: admin / admin123")
        print("- Clients: client1-client10 / password123")
        print("- Prestataires: provider1-provider5 / password123")

if __name__ == '__main__':
    init_database()

# ================================
# tests/test_models.py
# ================================

import unittest
from app import create_app, db
from app.models.user import User, UserType
from app.models.event import Event, EventType, EventStatus
from app.models.provider import Provider, ProviderCategory
from app.models.venue import Venue
from datetime import datetime

class ModelTestCase(unittest.TestCase):
    """Tests pour les modèles de données"""
    
    def setUp(self):
        """Configuration avant chaque test"""
        self.app = create_app('app.config.TestingConfig')
        self.app_context = self.app.app_context()
        self.app_context.push()
        db.create_all()
    
    def tearDown(self):
        """Nettoyage après chaque test"""
        db.session.remove()
        db.drop_all()
        self.app_context.pop()
    
    def test_password_hashing(self):
        """Test du hashage des mots de passe"""
        user = User(username='test', email='test@example.com')
        user.set_password('password123')
        
        self.assertFalse(user.check_password('wrongpassword'))
        self.assertTrue(user.check_password('password123'))
    
    def test_user_creation(self):
        """Test de création d'utilisateur"""
        user = User(
            username='testuser',
            email='test@example.com',
            first_name='Test',
            last_name='User',
            user_type=UserType.CLIENT
        )
        user.set_password('password123')
        
        db.session.add(user)
        db.session.commit()
        
        self.assertEqual(user.get_full_name(), 'Test User')
        self.assertEqual(user.user_type, UserType.CLIENT)
        self.assertTrue(user.check_password('password123'))
    
    def test_event_creation(self):
        """Test de création d'événement"""
        # Créer un utilisateur d'abord
        user = User(username='organizer', email='organizer@example.com')
        user.set_password('password123')
        db.session.add(user)
        db.session.commit()
        
        # Créer un événement
        event = Event(
            title='Test Event',
            organizer_id=user.id,
            event_type=EventType.PROFESSIONAL,
            status=EventStatus.DRAFT,
            total_budget=5000,
            expected_participants=50
        )
        
        db.session.add(event)
        db.session.commit()
        
        self.assertEqual(event.title, 'Test Event')
        self.assertEqual(event.organizer, user)
        self.assertEqual(event.status, EventStatus.DRAFT)
    
    def test_provider_creation(self):
        """Test de création de prestataire"""
        # Créer un utilisateur d'abord
        user = User(
            username='provider',
            email='provider@example.com',
            user_type=UserType.PROVIDER
        )
        user.set_password('password123')
        db.session.add(user)
        db.session.commit()
        
        # Créer le profil prestataire
        provider = Provider(
            user_id=user.id,
            company_name='Test Company',
            category=ProviderCategory.VENUE,
            description='Test description',
            base_price=1000
        )
        
        db.session.add(provider)
        db.session.commit()
        
        self.assertEqual(provider.company_name, 'Test Company')
        self.assertEqual(provider.user, user)
        self.assertEqual(provider.category, ProviderCategory.VENUE)
        self.assertEqual(provider.average_rating, 0.0)
        self.assertEqual(provider.total_ratings, 0)
    
    def test_venue_creation(self):
        """Test de création de lieu"""
        venue = Venue(
            name='Test Venue',
            city='Paris',
            max_capacity=100,
            base_price=500,
            is_active=True
        )
        
        db.session.add(venue)
        db.session.commit()
        
        self.assertEqual(venue.name, 'Test Venue')
        self.assertEqual(venue.city, 'Paris')
        self.assertTrue(venue.is_active)

# ================================
# tests/test_routes.py
# ================================

import unittest
from app import create_app, db
from app.models.user import User, UserType

class RouteTestCase(unittest.TestCase):
    """Tests pour les routes de l'application"""
    
    def setUp(self):
        """Configuration avant chaque test"""
        self.app = create_app('app.config.TestingConfig')
        self.app_context = self.app.app_context()
        self.app_context.push()
        self.client = self.app.test_client()
        db.create_all()
        
        # Créer un utilisateur de test
        self.user = User(
            username='testuser',
            email='test@example.com',
            first_name='Test',
            last_name='User'
        )
        self.user.set_password('password123')
        db.session.add(self.user)
        db.session.commit()
    
    def tearDown(self):
        """Nettoyage après chaque test"""
        db.session.remove()
        db.drop_all()
        self.app_context.pop()
    
    def login(self, username='testuser', password='password123'):
        """Helper pour se connecter"""
        return self.client.post('/login', data={
            'username': username,
            'password': password
        }, follow_redirects=True)
    
    def logout(self):
        """Helper pour se déconnecter"""
        return self.client.get('/logout', follow_redirects=True)
    
    def test_index_page(self):
        """Test de la page d'accueil"""
        response = self.client.get('/')
        self.assertEqual(response.status_code, 200)
        self.assertIn(b'Creative Cocktail', response.data)
    
    def test_login_logout(self):
        """Test de connexion/déconnexion"""
        # Test page de connexion
        response = self.client.get('/login')
        self.assertEqual(response.status_code, 200)
        
        # Test connexion réussie
        response = self.login()
        self.assertEqual(response.status_code, 200)
        
        # Test déconnexion
        response = self.logout()
        self.assertEqual(response.status_code, 200)
    
    def test_login_invalid_credentials(self):
        """Test de connexion avec identifiants invalides"""
        response = self.login('wronguser', 'wrongpassword')
        self.assertIn(b'incorrect', response.data)
    
    def test_protected_route_requires_login(self):
        """Test qu'une route protégée nécessite une connexion"""
        response = self.client.get('/dashboard')
        self.assertEqual(response.status_code, 302)  # Redirection vers login
    
    def test_dashboard_access_after_login(self):
        """Test d'accès au dashboard après connexion"""
        self.login()
        response = self.client.get('/dashboard')
        self.assertEqual(response.status_code, 200)
        self.assertIn(b'Tableau de bord', response.data)
    
    def test_providers_page(self):
        """Test de la page des prestataires"""
        response = self.client.get('/providers')
        self.assertEqual(response.status_code, 200)
        self.assertIn(b'prestataires', response.data)
    
    def test_venues_page(self):
        """Test de la page des lieux"""
        response = self.client.get('/venues')
        self.assertEqual(response.status_code, 200)
        self.assertIn(b'Lieux', response.data)

# ================================
# tests/test_api.py
# ================================

import unittest
import json
from app import create_app, db
from app.models.user import User
from app.models.venue import Venue
from app.models.provider import Provider, ProviderCategory

class APITestCase(unittest.TestCase):
    """Tests pour l'API REST"""
    
    def setUp(self):
        """Configuration avant chaque test"""
        self.app = create_app('app.config.TestingConfig')
        self.app_context = self.app.app_context()
        self.app_context.push()
        self.client = self.app.test_client()
        db.create_all()
        
        # Créer des données de test
        self.venue = Venue(
            name='Test Venue',
            city='Paris',
            max_capacity=100,
            is_active=True
        )
        db.session.add(self.venue)
        
        self.user = User(
            username='provider',
            email='provider@example.com',
            user_type='provider'
        )
        self.user.set_password('password123')
        db.session.add(self.user)
        db.session.flush()
        
        self.provider = Provider(
            user_id=self.user.id,
            company_name='Test Provider',
            category=ProviderCategory.VENUE,
            is_verified=True
        )
        db.session.add(self.provider)
        db.session.commit()
    
    def tearDown(self):
        """Nettoyage après chaque test"""
        db.session.remove()
        db.drop_all()
        self.app_context.pop()
    
    def test_search_venues_api(self):
        """Test de l'API de recherche de lieux"""
        response = self.client.get('/api/search/venues?q=Test')
        self.assertEqual(response.status_code, 200)
        
        data = json.loads(response.data)
        self.assertIsInstance(data, list)
        self.assertGreater(len(data), 0)
        self.assertEqual(data[0]['name'], 'Test Venue')
    
    def test_search_providers_api(self):
        """Test de l'API de recherche de prestataires"""
        response = self.client.get('/api/search/providers?category=lieu')
        self.assertEqual(response.status_code, 200)
        
        data = json.loads(response.data)
        self.assertIsInstance(data, list)
        self.assertGreater(len(data), 0)
        self.assertEqual(data[0]['company_name'], 'Test Provider')
    
    def test_api_error_handling(self):
        """Test de gestion d'erreurs API"""
        response = self.client.get('/api/nonexistent')
        self.assertEqual(response.status_code, 404)

# ================================
# tests/run_tests.py
# ================================

import unittest
import sys
import os

# Ajouter le répertoire parent au path pour l'import
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

def run_tests():
    """Exécuter tous les tests"""
    
    # Découvrir et charger tous les tests
    loader = unittest.TestLoader()
    start_dir = os.path.dirname(__file__)
    suite = loader.discover(start_dir, pattern='test*.py')
    
    # Exécuter les tests
    runner = unittest.TextTestRunner(verbosity=2)
    result = runner.run(suite)
    
    # Retourner le code de sortie approprié
    return 0 if result.wasSuccessful() else 1

if __name__ == '__main__':
    exit_code = run_tests()
    sys.exit(exit_code)

# ================================
# scripts/backup_db.py
# ================================

"""Script de sauvegarde de la base de données"""

import os
import subprocess
from datetime import datetime
from app import create_app

def backup_database():
    """Créer une sauvegarde de la base de données"""
    
    app = create_app()
    
    with app.app_context():
        # Récupérer les informations de connexion
        database_url = app.config['SQLALCHEMY_DATABASE_URI']
        
        # Parser l'URL de la base de données
        # Format: mysql+pymysql://user:password@host/database
        if 'mysql' in database_url:
            # Extraire les informations de connexion
            parts = database_url.split('/')
            database = parts[-1]
            auth_host = parts[-2].split('@')
            host = auth_host[-1]
            user_pass = auth_host[0].split('//')[-1].split(':')
            user = user_pass[0]
            password = user_pass[1] if len(user_pass) > 1 else ''
            
            # Créer le nom du fichier de sauvegarde
            timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
            backup_file = f'backup_creative_cocktail_{timestamp}.sql'
            backup_path = os.path.join('backups', backup_file)
            
            # Créer le répertoire s'il n'existe pas
            os.makedirs('backups', exist_ok=True)
            
            # Commande mysqldump
            cmd = [
                'mysqldump',
                '-h', host,
                '-u', user,
                f'-p{password}' if password else '',
                '--single-transaction',
                '--routines',
                '--triggers',
                database
            ]
            
            # Filtrer les éléments vides
            cmd = [arg for arg in cmd if arg]
            
            try:
                with open(backup_path, 'w') as f:
                    subprocess.run(cmd, stdout=f, check=True)
                
                print(f"Sauvegarde créée avec succès: {backup_path}")
                return backup_path
                
            except subprocess.CalledProcessError as e:
                print(f"Erreur lors de la sauvegarde: {e}")
                return None
        else:
            print("Type de base de données non supporté pour la sauvegarde")
            return None

if __name__ == '__main__':
    backup_database()

# ================================
# scripts/restore_db.py
# ================================

"""Script de restauration de la base de données"""

import os
import subprocess
import sys
from app import create_app

def restore_database(backup_file):
    """Restaurer la base de données depuis un fichier de sauvegarde"""
    
    if not os.path.exists(backup_file):
        print(f"Fichier de sauvegarde non trouvé: {backup_file}")
        return False
    
    app = create_app()
    
    with app.app_context():
        database_url = app.config['SQLALCHEMY_DATABASE_URI']
        
        if 'mysql' in database_url:
            # Parser l'URL de la base de données
            parts = database_url.split('/')
            database = parts[-1]
            auth_host = parts[-2].split('@')
            host = auth_host[-1]
            user_pass = auth_host[0].split('//')[-1].split(':')
            user = user_pass[0]
            password = user_pass[1] if len(user_pass) > 1 else ''
            
            # Commande mysql pour restaurer
            cmd = [
                'mysql',
                '-h', host,
                '-u', user,
                f'-p{password}' if password else '',
                database
            ]
            
            cmd = [arg for arg in cmd if arg]
            
            try:
                with open(backup_file, 'r') as f:
                    subprocess.run(cmd, stdin=f, check=True)
                
                print(f"Base de données restaurée avec succès depuis: {backup_file}")
                return True
                
            except subprocess.CalledProcessError as e:
                print(f"Erreur lors de la restauration: {e}")
                return False
        else:
            print("Type de base de données non supporté pour la restauration")
            return False

if __name__ == '__main__':
    if len(sys.argv) != 2:
        print("Usage: python restore_db.py <backup_file>")
        sys.exit(1)
    
    backup_file = sys.argv[1]
    success = restore_database(backup_file)
    sys.exit(0 if success else 1)